### PR TITLE
fixes #69

### LINKED ISSUE #69: Build show errors/warnings
Hola there, it's me again !
Was trying to make a docker container for this, but some errors/warnings pop up while building
The website itself does work, but I want to make sure that this does not affect anything else
seems related to [vercel/next.js#48192 (comment)](https://github.com/vercel/next.js/discussions/48192?sort=top#discussioncomment-7300963)
the errors:
```
Warning: React Hook useEffect has missing dependencies: 'startTimer' and 'updateTime'. Either include them or remove the dependency array.  react-hooks/exhaustive-deps
(.....)
 Warning: React Hook useEffect has a missing dependency: 'growBonsai'. Either include it or remove the dependency array.  react-hooks/exhaustive-deps
(.....)
Warning: You have opted-out of Automatic Static Optimization due to `getInitialProps` in `pages/_app`. This does not opt-out pages with `getStaticProps`
(.....)
Static worker unexpectedly exited with code: null and signal: SIGINT (repeated ~14 times)
```
Is it fine to ignore these ?

### PR DESCRIPTION
**Pull request by Magniquick**
fixes #69 (nice) by allowing minor version changes in next.js
ABSOLUTELY not a web dev, so I may have done this wrong.
Don't know if [deleting yarn.lock](https://github.com/allister-grange/startertab/commit/3c5aff8fe37716a480ef32a9ee24fb7724f2b9f7) was necessary, but it does work now : P.
now basically only a single warning remains, namely:
```sh
Warning: You have opted-out of Automatic Static Optimization due to `getInitialProps` in `pages/_app`. This does not opt-out pages with `getStaticProps`
Read more: https://nextjs.org/docs/messages/opt-out-auto-static-optimization
```
(and one about `Invalid next.config.js options detected, "env.xyz" is missing, expected string`, but thats for strava and API client, neither of which I use or have set the env vars for in the env.local file - so it _should_ be fine )

### CODE REVIEW

**Comment by Magniquick** [comment]
I've given up on fixing the ``Invalid next.config.js options`` (sorry for all those commits), if it breaks something, let me know : (

**Comment by Magniquick** [comment]
never mind, I fixed that by creating an .env.production with the same content as .env.local  !
(going to reset to head and reapply the fixes, to make this pr more manageable)

**Comment by allister-grange** [comment]
Sorry @Magniquick you can't just yeet out the yarn.lock file like that, it's needed to keep dependencies around for each run of `yarn install` across developer's machines.

However, I have taken inspiration from this commit and chucked in the `^` on the _next_ version so that the build warning is gone. 

The new code is on the main branch now!

**Comment by Magniquick** [comment]
Thanks !

**Comment by Magniquick** [comment]
Thanks !
@allister-grange do you have any clue why next build does not not load .local.env ? It does work when I manually set the environment values.
Is this reproducible on your end ?

**Pull request closed without merging**
